get-data:
	mkdir -p data
	wget http://www.quantum-machine.org/gdml/data/npz/benzene_old_dft.npz -O data/benzene_dft.npz
	wget http://www.quantum-machine.org/gdml/data/npz/uracil_dft.npz -O data/uracil_dft.npz
	wget http://www.quantum-machine.org/gdml/data/npz/naphthalene_dft.npz -O data/naphthalene_dft.npz
	wget http://www.quantum-machine.org/gdml/data/npz/salicylic_dft.npz -O data/salicylic_dft.npz
	wget http://www.quantum-machine.org/gdml/data/npz/malonaldehyde_dft.npz -O data/malonaldehyde_dft.npz
	wget http://www.quantum-machine.org/gdml/data/npz/ethanol_dft.npz -O data/ethanol_dft.npz
	wget http://www.quantum-machine.org/gdml/data/npz/toluene_dft.npz -O data/toluene_dft.npz
	wget http://www.quantum-machine.org/gdml/data/npz/aspirin_dft.npz -O data/aspirin_dft.npz
